"""init

Revision ID: a523404b6aae
Revises: 
Create Date: 2023-10-21 15:27:55.979359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a523404b6aae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practical_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=32000), nullable=False),
    sa.Column('language', sa.Enum('JAVA', 'PYTHON', 'C', name='programlanguage'), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=255), nullable=False),
    sa.Column('testing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theoretical_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=32000), nullable=False),
    sa.Column('testing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('poster', sa.UUID(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=32000), nullable=False),
    sa.Column('type', sa.Enum('PRACTICE', 'INTERNSHIP', name='vacancytype'), nullable=True),
    sa.Column('state', sa.Enum('CLOSED', 'OPENED', name='vacancystate'), nullable=True),
    sa.Column('test_time', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=320), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['theoretical_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_uploaded', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.VARCHAR(length=32000), nullable=False),
    sa.Column('type', sa.Enum('THEORETICAL', 'PRACTICAL', name='testtype'), nullable=False),
    sa.Column('correct_percent', sa.INTEGER(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('percent', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['testing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_table('testing')
    op.drop_table('files')
    op.drop_table('answer_options')
    op.drop_table('vacancies')
    op.drop_table('theoretical_questions')
    op.drop_table('practical_questions')
    # ### end Alembic commands ###
