"""vacancy enum type update

Revision ID: efc3aff388f9
Revises: 23d48dfd9b04
Create Date: 2023-10-21 23:34:48.833411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc3aff388f9'
down_revision: Union[str, None] = '23d48dfd9b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'type',
               existing_type=postgresql.ENUM('PRACTICE', 'INTERNSHIP', name='vacancytype'),
               nullable=False)
    op.alter_column('vacancies', 'state',
               existing_type=postgresql.ENUM('CLOSED', 'OPENED', name='vacancystate'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'state',
               existing_type=postgresql.ENUM('CLOSED', 'OPENED', name='vacancystate'),
               nullable=True)
    op.alter_column('vacancies', 'type',
               existing_type=postgresql.ENUM('PRACTICE', 'INTERNSHIP', name='vacancytype'),
               nullable=True)
    # ### end Alembic commands ###
